name: prerelease

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  npm:
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: make package
      - run: 'echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc'
      - run: 'npm publish ./pkg --tag next'
