name: release

on:
  push:
    branches:
      - master

jobs:
  npm:
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: make package
      - run: 'echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc'
      - run: |
          git config user.name 'manifoldco-dangerzone'
          git config user.email 'admin+github-bot-dangerzone@manifold.co'
      - run: npm run release -- --preRelease=next --ci
